version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    env_file: ./trackmeapi/.env
    volumes:
      - db-data:/var/lib/postgresql/db-data

  app:
    build: ./trackmeapi/
    env_file:
      - ./trackmeapi/.env
    user: $UID
    volumes:
      - ./trackmeapi:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
